### ISSUE TITLE
Partial Refund

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#157]
When a discount is added, it can change the price of something which has already been purchased. In that case, the user should automatically receive a refund for the amount of the discount.

**Comment by harrislapiroff** [comment]
I'm renaming this "Partial Refund" because I think it should be implemented more generally than part of the discount system. Let me know if you disagree.

A lot of events have refund policies that offer partial refunds after a certain date. (Usually this is to make sure there's an incentive for people to withdraw early if they know they won't be able to attend, but also to account for the registration hassle of dealing with last minute withdrawals.)

**Comment by harrislapiroff** [comment]
To clarify this issue in the current state of the code: Currently organizers can issue a refund on an entire financial transaction. It would nice to be able to issue refunds: 1. per item and 2. of arbitrary amounts, with the latter being more important.

**Comment by harrislapiroff** [comment]
(Currently organizers have to go through the payment processor to handle partial refunds.)

**Comment by harrislapiroff** [comment]
I'm going to look at this this week.

**Comment by melinath** [comment]
The big part that needs you @harrislapiroff is figuring out the interface. I.e. we need an intuitive way for event organizers to select the items they want to refund. This could mean reconsidering the entire organizer interface for managing receipts (hypothetically. Or not.) The backend is simple once that interface is sorted out.

**Comment by melinath** [comment]
We could have some way for the item selection to have a custom refund amount attached (which could potentially be zero.)

**Comment by harrislapiroff** [comment]
From the discussion on #380, here's a quick sketch of what I imagine decoupling refunds from carts/items could look like:

![refunds](https://cloud.githubusercontent.com/assets/296631/14960124/0f8590d6-1061-11e6-9174-47319191654c.png)

**Comment by harrislapiroff** [comment]
An organizer could hypothetically check no items and still enter a refund amount in order to give a post-hoc discount.

**Comment by melinath** [comment]
That all sounds great. The only remaining question in my mind is: how do they get there from the receipt view? I guess we could just add another tab for now?

**Comment by melinath** [comment]
(We should also make clear when refunding things that attendees with no items will be deleted.) (If they will be deleted.)

**Comment by harrislapiroff** [comment]
(ooh good point.)

I think an action should be directly on the table row, if possible, actually. Though the whole tables situation is a little wonky, since there's a good chance they'll search for attendee rather than order. I'll need to think thought that.

**Comment by harrislapiroff** [comment]
I'm picturing the thing i mocked up as a modal.

**Comment by harrislapiroff** [comment]
We should also probably be recording a history of actions taken on a user in a stream form, so an organizer can reconstruct if anything got messed up by another organizer (or themselves) later in the process. Are we already doing that? Otherwise, maybe that's another ticket.

**Comment by melinath** [comment]
We are not already doing that.

**Comment by melinath** [comment]
FWIW I feel pretty strongly that this should work within the framework we've already established for interacting with Orders i.e. the order detail page. There should be one obvious way to do it. Adding a button might be easier to use, but it would also be more confusing.

**Comment by harrislapiroff** [comment]
"There should be one obvious way to do it." I appreciate the sentiment, but I don't actually think it is a good approach to UX. There should be a way to do it in the places where a user is most likely to look, even if that means in multiple places. You don't have the same problem that you do with programming where having more than one way to do it means you have to learn all of them. When you're a user you only have to find one way to do it and then forget about it until next time.

I actually have been generally unhappy with the overloading of the order detail page for a while. Organizers, in my experience, are often working with orders in bulk, not one at a time. Putting all the actions on the detail page makes that more difficult to do.

**Comment by harrislapiroff** [comment]
(Stripe, for one example, offers the ability to refund both on the list view and the detail view.)

**Comment by harrislapiroff** [comment]
It's the same argument I was making in #287, basically. Though we didn't resolve that one either, yet.

**Comment by harrislapiroff** [comment]
That having been said, there is a valid concern about a table row not having a lot of space and probably ideally being reserved for the most common actions...

**Comment by melinath** [comment]
Stripe's refund modal:

![screen shot 2016-05-02 at 10 21 05 pm](https://cloud.githubusercontent.com/assets/299979/14975254/a47cac4e-10b4-11e6-9c7e-d370c609b4ee.png)

I have a couple of concerns:

1. Like you said, the table rows are already pretty darn full (whereas on Stripe's site you just see the amount, id, and timestamp.)
2. I don't want to accidentally end up redoing the entire table view just to add a button.
3. Stripe's refund process is still per-transaction and only deals with dollar amounts, whereas our refund process needs to handle an arbitrary number of transactions and also handle refunding the items related to them. (Or we could stick with per-transaction refunds.)

I think you're right that organizers wouldn't want to page back and forth between views. What do you think about putting refund handling on the finances table rather than the orders table, though?

**Comment by harrislapiroff** [comment]
I think it's impossible to find any particular financial transaction since that table doesn't have any filtering and it doesn't list anyone's names. Otherwise I'd maybe be okay with that. Maybe we should pull someone over to a computer hand them a test event and tell them to try to refund John Appleseed's order and see what they do. User testing!

**Comment by harrislapiroff** [comment]
I think in this case what I might like to do is agree that putting the refund interface on the order detail page is the MVP for this feature, but I do want to continue thinking about how actions like this and marking checks as paid can be made more easily accessible (perhaps through the table view) in the future.

**Comment by harrislapiroff** [comment]
Soooo, looking into this further, I think this _is_ made tricky by the fact that we keep track of whether a transaction is refunded or not. I think ultimately that _is_ actually going to be a structure we have to get rid of—I think supporting partial refunds, even supporting just webhooks from stripe, will make it untenable to determine what qualifies as a "refunded" or "not refunded" transaction.

I think ideally, at least from a UX perspective, this is how I would like to think of the objects involved. I'm agnostic about how this is represented on the backend:

* An "Order" is a relationship between a certain user and a certain event. It can contain items that have been purchased
* A "Transaction" is an event that occurs that includes a financial exchange and/or adding or removing items to the "Order." Usually the financial exchange will correspond with the item exchange, but not always. (I.e., this would allow an organizer to add items to a particular order for free or refund an arbitrary amount of money that doesn't necessarily correspond to the items—if any—being added or removed).

This will add a lot more flexibility than we currently offer in terms of CRUD and will save organizers the trouble of our advice often being, "have the user do a thing to fix this," by empowering organizers to create their own transactions. I realize this is a more complex overhaul than implementing partial refunds is supposed to be, but I'm having trouble figuring out how else arbitrary refunds could work within the current data structure.

**Comment by melinath** [comment]
We talked about this a bit. Short summary:

* This is basically already how everything works.
* Transaction.refund() accepts arbitrary amount and bought_items arguments.

Potential issues:

* Need to make sure to pass in an empty list/qs if no bought_items are being refunded, otherwise all items will be refunded.
* display of refunded transactions on a receipt currently relies on item price. Since amount is not going to be tied to items, this doesn't make sense any more.

**Comment by harrislapiroff** [comment]
Stephen beat me to the punch in summarizing our call.

**Comment by harrislapiroff** [comment]
Probably the best way to implement this is with a `TransactionRefundForm` whose constructor takes a `Transaction` object and creates the appropriate bool fields upon initialization, yeah?

**Comment by melinath** [comment]
Ssssssure?

**Comment by harrislapiroff** [comment]
LEAST ENTHUSIASTIC RESPONSE

**Comment by melinath** [comment]
I don't know what you're talking about but yes making a Form sounds like a good idea, and setting some default values in the constructor also sounds good.

**Comment by harrislapiroff** [comment]
Work on this is being done on this branch: https://github.com/littleweaver/django-brambling/tree/partial-refunds

Here's what it looks like so far.

![screenshot 2016-05-09 14 45 51](https://cloud.githubusercontent.com/assets/296631/15124116/c134d7f4-15f4-11e6-9cd6-3e6e26d7af76.png)
![screenshot 2016-05-09 14 46 03](https://cloud.githubusercontent.com/assets/296631/15124120/c3d43414-15f4-11e6-97a2-7c3661e7a6dd.png)

**Comment by melinath** [comment]
Resolved with merge of #803
