### ISSUE TITLE
Ability to change pass type from attendee info page

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#175]
Can we get a dropdown on that page that allows you to switch from that pass to any other pass?

**Comment by melinath** [comment]
The attendee information is attached to the pass. I'm not convinced that it would make sense to switch which pass it's attached to. Although since we have separate pages for each user, the cost of copy-pasting is much higher....

**Comment by melinath** [comment]
This was resolved as a side effect of #507 (removing item categories).
