### ISSUE TITLE
Clean up behavior of "next step button"

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#209]
Right now, it sometimes looks like it should have submit button functionality when it does not. Also, it and the countdown should maybe not be at the top of the page. See https://github.com/littleweaver/django-brambling/commit/37f4f8a2263e#commitcomment-8032523 and nearby comments

**Comment by harrislapiroff** [comment]
My going theory is to make more of the views single column and have a static side column that has the timer, and the next step button.

**Comment by harrislapiroff** [comment]
Gonna try it.

**Comment by harrislapiroff** [comment]
Resolved by bf65fd06185e83ff208f3b4bbfef08b0beb1756b
