### ISSUE TITLE
Hide reserved orders by default from organizer

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#229]
I think we should hide reserved orders from organizers by default, especially if we implement #223. In most cases reserved orders will be orders-in-progress (potentially orders that have been backed out of and will never actually be purchased) and should not show up with the completed orders.

Maybe we can display somewhere an "X orders in progress" button that would let organizers look at those.

**Comment by melinath** [comment]
+1

**Comment by melinath** [comment]
This is resolved as part of #303 (specifically commits 4ff35578235b375500ec53147eaf9e0912fe94d6 and df17d624b71229ca693c980b28364c67b675495f)
