### ISSUE TITLE
Save multiple attendees per account rather than associating account with one attendee

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#233]
Right now, accounts have names attached and save one attendee profile, but if, for example, you generally sign up as a pair, it doesn't make so much sense for only one of you to be the primary person on the account, and never save the other person's information.

#### Proposal:
Remove name from user information. Just use email/password for both login and signup.
Save a collection of attendee profiles, with the ability to remove or edit them.
In attendee/pass assignment, you can use existing attendees or create new ones.

**Comment by melinath** [comment]
As a corollary, stored housing data should be saved as part of the attendee, not as part of the user. This will squash the idea of housemates co-editing a house's information, but that was probably unnecessary anyway.

**Comment by melinath** [comment]
Also related: #312
