### ISSUE TITLE
Custom Forms/Survey

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#243]
Organizers should be able to collect custom sets of data. Dance events often have a lot of information that they like to collect which is unpredictable and will vary pretty widely from event to event.

E.g., YDW needs to collect saturday night activity ideas. Blues events probably want to collect information about competition registrations?

Potential implementations:

* Google form integration (potentially messy; organizers have to deal with a google spreadsheet *and* our tables)
* Our own custom django implementation of custom forms (lot of work and testing)
* Something else?

**Comment by nmorduch** [comment]
Could we allow just an embed of another form service? Google forms or otherwise. We even could do this by just letting the organizer put some html into something like the survey page. That way people wouldn't have to leave our site to use it, but we wouldn't have to make it. Though I think that eventually we definitely want our own django implementation.

**Comment by melinath** [comment]
So the current plan is (roughly) that we'll implement a simple version of custom forms this week (exact format TBA) then iterate on it over the course of the month.

Inspiration: [Bartleby](https://github.com/melinath/philo/tree/forms/philo/contrib/bartleby)

**Comment by melinath** [comment]
UI discussion: https://docs.google.com/document/d/1sNmaaDU0qQ-xzg7W7_v8vJzc-q9edVZDTsNZk6CDtQQ/edit#heading=h.ifa7fx46kqx2

None of the plug-and-play options out there do quite what we need.

**Comment by melinath** [comment]
We didn't quite follow the schedule laid out in that discussion... but I think we're in a good place for this ticket. We should create a new ticket for the next stage (or for individual things that will be added) and then close this.

**Comment by nmorduch** [comment]
Added lots of issues, all referenced above and given the label Custom Forms. Closing.
