### ISSUE TITLE
Change message about sending checks after last day to send checks

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#289]
ie, if checks have to be sent by 12/30, on 12/31 change the message on the order summary page to say, "if you haven't yet sent your check, organizer wants you to do x"

**Comment by melinath** [comment]
We should also check whether the check's been confirmed by the organizer, and if so, display a different message altogether. Which we maybe already do?

**Comment by harrislapiroff** [comment]
We already do that ^
