### ISSUE TITLE
Refunded items display in order summary

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#290]
If an attendee has refunded items, group them together under "refunded" rather than showing them in the same list. In the payments table, say what each refund was for.

**Comment by melinath** [comment]
This is related to the original bug reported in #260.

**Comment by melinath** [comment]
@nmorduch is this something that you can fix in the templates, or do you need different template variables?

**Comment by nmorduch** [comment]
I'm not really sure. I think I tried and the way it works now, you cycle through items and then add another row to ones that are refunded. It's probably possible to cycle through once to display non-refunded items, then again to display only refunded items, but there is probably a more efficient way to do that, where there is an actual list for each, rather than just a combined list.

**Comment by melinath** [comment]
This is related to #316.

**Comment by melinath** [comment]
They also still show up on the Attendee page, but can't actually be edited because attendee editing excludes refunded passes.

**Comment by melinath** [comment]
Resolved with merge of #504.
