### ISSUE TITLE
ensure order numbers can be hand-written

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#291]
ie do not use the characters `lI1oO0` and possibly others depending on how serious we want to be. see http://www.ismp.org/newsletters/acutecare/articles/20090702.asp and http://psqh.com/july-august-2014/misidentification-of-alphanumeric-symbols (quick search results) for more examples of confusion

**Comment by melinath** [comment]
@nmorduch: I think you can take this one. You'll want to look into the `get_random_string` function in `django.utils.crypto`. We use it in `brambling/views/orders.py` to generate new codes for orders - it takes a second argument which is the alphabet to choose from.

I'd recommend setting the alphabet as a constant at the top of the `orders.py` file, right after `ORDER_CODE_SESSION_KEY`.

**Comment by nmorduch** [comment]
Did not remove characters such as `cCsS2ZvV` because that started to feel excessive. Limited it to removing the ones listed above, which can be hard to distinguish on a screen.
