### ISSUE TITLE
pending payments display in order summary

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#292]
display received payments & refunds in one list, with a subtotal, then below that add pending payments, with a total.

rather than just all payments in one list, with a column for whether they've been received.

**Comment by melinath** [comment]
@nmorduch This seems like you'll probably need differently structured data. Does that seem accurate?

**Comment by melinath** [comment]
i.e. it can't be fixed by just changing the templates.

**Comment by nmorduch** [comment]
Yeah. And I think that's it's important for OJDF, because I also want to display in the list of all orders how much each order has in outstanding payments.

**Comment by nmorduch** [comment]
I think that in all cases, promising to send a check should not mean that you are marked as paid. You should be marked as pending payment (though with your order complete).
It's super confusing for the organizers otherwise; when everyone pays by check, the event summary says that none of the payments are outstanding, rather than giving a useful overview of how much money has actually been received.

**Comment by melinath** [comment]
+1

**Comment by melinath** [comment]
As part of this, we should also distinguish between cash in hand and pending payments in the event summary data.

**Comment by melinath** [comment]
Partially resolved with merge of #303
