### ISSUE TITLE
List events hosted in other places

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#293]
As long as we're compiling lists of events & information on them, we could also add those events into Dancerfly, making it an easy place to go to search for events.

**Comment by melinath** [comment]
This could also function as advertising. If we got enough events in there and a good enough quality of content...

**Comment by melinath** [comment]
But it would also be a PITA to keep updated. But it might be beneficial to us anyway, while we're chasing down leads.

**Comment by harrislapiroff** [comment]
Duplicate of #288?

**Comment by melinath** [comment]
HAH. Whoops.

**Comment by harrislapiroff** [comment]
Oh, I guess you're talking about maintaining a calendar ourselves, so not really a duplicate. I'm -1 on that idea. Or maybe, like, -0.5. I'd be willing to do it, but only with the goal that eventually it would be self-maintained by event organizers.
