### ISSUE TITLE
Easier item creation

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#297]
tbh it's currently confusing & annoying & a pain. Can we have a quick-add option? I will make some sketches.

**Comment by melinath** [comment]
Sounds nice to me.

**Comment by melinath** [comment]
This is what Square's item creation system looks like - I like it a lot, generally speaking, but it does lack the features we offer (of course).

![square](https://cloud.githubusercontent.com/assets/299979/5685821/f097bae2-97f2-11e4-87de-07f5d866d40c.png)

**Comment by nmorduch** [comment]
That does look good. I'll look at applying something like that to what we have.

**Comment by melinath** [comment]
Folks are running into this as a serious issue; it would be great if we could try to find some kind of resolution.

**Comment by melinath** [comment]
By making the UI more intuitive and/or having examples of what to enter.

**Comment by harrislapiroff** [comment]
I just sketched up an item creation UI, but basically it's more or less the same as the Square UI above, I'm realizing. So, uh, yeah. I'm picturing the advanced options folding out the way the the options for the mail/check payment processor or the more name options fold out. (And similarly having them stay there if they've been modified from their defaults.) 

Even though it looks like a table, this will probably be easiest _not_ coded as a table.

![file may 14 5 47 20 pm](https://cloud.githubusercontent.com/assets/296631/7642758/b4bf3686-fa61-11e4-901e-82b36fbefa5e.jpeg)

**Comment by harrislapiroff** [comment]
This will rely on #510, probably.

**Comment by harrislapiroff** [comment]
We should also provide examples in help text (or even templates/defaults? separate ticket, maybe). Here are some thoughts:

* NAME: e.g., Registration, T-Shirt, Meal
* ITEM OPTION NAME: e.g., Saturday Only, Small, Lunch

**Comment by melinath** [comment]
Oh hey this is resolved with the merge of #532 :-)
