### ISSUE TITLE
Organizations of event managers

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#300]
Being a member of an organization allows you to create and edit any event owned by that organization.

Each organization should have a page with a list of events and any organization information. Possibly related to #227, or could just have a website link and text field.

**Comment by melinath** [comment]
I think the organization should also have other information. Highest priority: the organization's favored payment configuration and the organization's locale info. This would give us a mechanism to allow limited event creation by non-superusers and could help streamline event creation overall for organization members.

**Comment by nmorduch** [comment]
:+1:

**Comment by melinath** [comment]
Resolved by a4a975453f9143d16096f374da3df5c5f59ecbbd
