### ISSUE TITLE
Support for yearly events

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#301]
maybe something like
dancerfly.com/eventname/2015
and dancerfly.com/eventname can redirect to the current one

Related to #299, maybe

**Comment by harrislapiroff** [comment]
I don't think the solution to this ticket is to give annual events should have their own URL scheme. I think there are solutions that would work more generally including for things like monthly events, biannual events, events that recur irregularly, etc.

1. Encourage people to use things like `dandelion-romp-2015` as their slugs.
2. Alongside #300 give events URLs like `/<organization>/<event-slug>/`.
3. Give events URLs like `/<user>/<event-slug>/`.
4. Force-prepend unique IDs to event slugs, like Tumblr does for posts.

Solutions 1 and 2 are my favorites. Solution 4 is my least favorite.

**Comment by nmorduch** [comment]
I like nos. 1 and 2 also.

**Comment by melinath** [comment]
I prefer #1, since it allows us to have `/orgs/<org-slug>/` without the further nesting of `event-slug`.

But I would also be down with `/<year>/<event-slug>/' potentially with a drilldown list functionality.

**Comment by harrislapiroff** [comment]
If it's between those two I have a preference for #1 since not all recurring events are annual. Though I'm curious why you don't want to allow orgs to occupy a root-level URL slug. URLs like `http://dancerfly.com/ydw/2015` or `http://dancerfly.com/leaf/spring2015/` make a lot of sense to me.

**Comment by harrislapiroff** [comment]
Though I suppose slug uniqueness enforcement/non-enforcement would get complex if we had both standalone events and orgs occupying the same URL structure.

**Comment by harrislapiroff** [comment]
Also OpenDance apparently uses a form and cookies to keep track of what year of an event you are looking at??

**Comment by melinath** [comment]
Yeah, the biggest issue is having events and orgs share the same slug-space. Though we could probably make it work.

But there's also the issue that not all orgs would make sense to organize that way. YDW is the name of the org, but it's also the name of the event.

As opposed to cmDance, which runs Lindy Diversion, Denver Tango Week, Lindy On The Rocks, Denver Vintage Jazz Festival, and Rocky Mountain Balboa Blowout. Or Groove Juice Swing, which runs Slow Dance Soiree and Stompology.

The org name is not necessarily how people know the event. It's just another thing for them to remember.

**Comment by harrislapiroff** [comment]
Hm. That's an interesting point. But in those cases, is the concept of an organization that mirrors real-world organizations still useful for those events? I thought the point of an organization was to group events together.

**Comment by harrislapiroff** [comment]
Maybe I'm just not understanding what the purpose of an org is, which is maybe a separate issue.

**Comment by melinath** [comment]
Not in my mind. Like, I think it makes sense to have a concept of a series of events, but I think it makes sense to have a *separate* concept of orgs that handle shared / default permissions / settings.

For example, if we were to take on a client that used us for series classes, and they started 10 or more different series classes every six weeks, those "events" wouldn't necessarily be part of the same series, but they would absolutely be part of the same organization. And it would be a PITA to manage them any other way. (Although for that situation, `<org-slug>/<event-slug>` might make sense...)

**Comment by nmorduch** [comment]
I think I would do `org/event`, and if it's like ydw, you have `ydw/2015` and if it's like cmdance, you have `cmdance/lindy-diversion-2015`

**Comment by nmorduch** [comment]
and then if someone goes to `dancerfly.com/ydw` there would be a link from there to `dancerfly.com/ydw/2015` so it would be ok

**Comment by melinath** [comment]
It sounds like we might want to have *all* events be run by "organizations", then? i.e. we would move all the permission handling (inviting editors, etc.) up to the organization level? I'd be down with that. It would fix the namespacing issue and it would keep us from having duplicate permissioning data on the org and event.

**Comment by harrislapiroff** [comment]
I would be interested in doing that, but I also feel like I need to meditate on this question a while longer before I'm sure what I want, haha.

**Comment by melinath** [comment]
So... a question on my mind is this: will people be putting this address on flyers and event materials? I think so. Which means there's a case to be made for ensuring the URL can be as short as possible.

But OTOH that's partially their responsibility, and also they can just use a URL shortener.

**Comment by melinath** [comment]
I'm leaning extremely strongly in favor of doing `/org-slug/event-slug/` for *all* events and having a "flexible" interpretation of what an "organization" can be - i.e. in general paralleling real-world orgs, but not necessarily.

**Comment by melinath** [comment]
Resolved by #a4a975453f9143d16096f374da3df5c5f59ecbbd
