### ISSUE TITLE
Prepopulate.js does not work if Grappelli is installed

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#310]
Because grappelli's version of prepopulate calls for `grp.jQuery` instead of `django.jQuery`

https://github.com/littleweaver/django-brambling/blob/master/brambling/templates/brambling/event/organizer/create.html#L16

**Comment by harrislapiroff** [comment]
This wouldn't be an issue because we don't use grappelli on the live server, but I kinda would like to eventually. And I think it's in the settings on our dev servers.

**Comment by melinath** [comment]
@harrislapiroff it seems like this is something @nmorduch could handle, since you're pretty full up on other things
