### ISSUE TITLE
Check text

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#314]
The check text in the final `else` [here](https://github.com/littleweaver/django-brambling/blob/master/brambling/templates/brambling/event/order/_check_payment_info.html) should indicate that the organizer has not marked the check as received and that the attendee needs to make sure it's received. (Currently it says "If you've already sent in your payment, great!")

**Comment by melinath** [comment]
This has an open pull request awaiting comments from @harrislapiroff.
