### ISSUE TITLE
Payment form UI

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#326]
Different payment methods should be part of the same accordion or tab interface. Currently the two stripe options act as an accordion together but not with the other payment options. The stripe security note should probably be moved _inside_ the Stripe payment panels (even if that means duplicating it).

![screenshot 2015-02-07 13 19 40](https://cloud.githubusercontent.com/assets/296631/6093236/0a2c49f6-aecc-11e4-862c-a031d7578ad6.png)

**Comment by melinath** [comment]
Resolved with merge of receipt redesign.
