### ISSUE TITLE
Automatically mark confirmation fields if field is edited

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#33]
Some of the fields for handling housing require confirmation of the field status. This is meant to require people to take a moment to think about the field. But if they edit the field, they're already thinking about it - so we should check the box. (Either on focus or on change.)

**Comment by melinath** [comment]
@nmorduch reassigning you since you're feeling more confident about JS

**Comment by nmorduch** [comment]
So I started working on this and I actually feel that it's pretty weird, for a few reasons.

1. The confirmation question is placed inconsistently. It should probably be once at the end of each panel.
1. It'll feel weird if when you change one of a few form fields, suddenly the confirmation is marked as true, even though you may know that another field still needs changing.

I propose a different solution, in which there are no confirmation questions, but if you have selected "I want to house visiting dancers" then clicking "next step" takes you to an easier-to-read display of your housing information, and at the bottom of that page you confirm and go to the next step.

**Comment by melinath** [comment]
I think that makes sense. We could postpone this until the new housing system is implemented (#312)

**Comment by melinath** [comment]
Closing this since it'll be obviated by saved attendees.
