### ISSUE TITLE
Fix z-index bugs during modals.

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#338]
There are some strange situations when modals pop up and some content is on top of the modal that shouldn't be. Simple example, when you're trying to refund an order.

![screen shot 2015-02-10 at 6 27 24 pm](https://cloud.githubusercontent.com/assets/299979/6140879/84c84d9e-b152-11e4-8e9a-3c2f27ee6f30.png)

Also, when you're shopping and run out of time.

![screen shot 2015-02-10 at 6 29 45 pm](https://cloud.githubusercontent.com/assets/299979/6140905/d7fb0d62-b152-11e4-8d2c-debc8092d0c9.png)

**Comment by melinath** [comment]
Also, the close button in the modal title area (on order/attendee filter views) is *below* the modal title, which means it is unclickable.

**Comment by nmorduch** [comment]
I made the second comment into its own issue #375 ^

**Comment by nmorduch** [comment]
Note:

```scss
//-- Z-index master list
//
// Warning: Avoid customizing these values. They're used for a bird's eye view
// of components dependent on the z-axis and are designed to all work together.
//
// Note: These variables are not generated into the Customizer.
$zindex-navbar: 1000 !default;
$zindex-dropdown: 1000 !default;
$zindex-popover: 1060 !default;
$zindex-tooltip: 1070 !default;
$zindex-navbar-fixed: 1030 !default;
$zindex-modal: 1040 !default;
```

**Comment by melinath** [comment]
So... did we customize them? What happened here?

**Comment by nmorduch** [comment]
I might be better able to look into this if the "refund order" button worked for me :p

**Comment by nmorduch** [comment]
The :recycle: button (i know it doesn't look exactly like that) did bring up a modal but with no backdrop
