### ISSUE TITLE
Mandrill stripping linebreaks?

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#351]
![screenshot 2015-02-15 17 01 32](https://cloud.githubusercontent.com/assets/296631/6205198/6af71658-b534-11e4-9596-888bd7570ae9.png)

Maybe it interprets all emails as HTML emails?

**Comment by melinath** [comment]
Our mail utils were sending the unformatted text as an HTML message. Whoops! (Not Mandrill's fault.)
