### ISSUE TITLE
Item Assignment Buggy

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#387]
Non-pass item assignment seems to be sort of buggy. Naomi and I ran into a few things including:

* Having a single item show up for multiple attendees.
* Having an item show up with the message "all items in order must be assigned to an attendee" but no option to assign the item to an attendee.
* Just generally unpredictably and wonky behavior.

This whole view should probably be audited.

**Comment by harrislapiroff** [comment]
![screenshot 2015-03-03 18 44 02](https://cloud.githubusercontent.com/assets/296631/6475156/4b30fed0-c1d5-11e4-82cd-9140db6fa1b7.png)

**Comment by harrislapiroff** [comment]
Here's an illustrative screen shot:

![screenshot 2015-03-05 11 08 21](https://cloud.githubusercontent.com/assets/296631/6508650/15d87066-c328-11e4-8c7b-42e623b2234d.png)

**Comment by melinath** [comment]
Okay, it looks like there's an unassigned medium t-shirt over on the right side.

**Comment by melinath** [comment]
Oh, you mean you can't, like, drag the item to assign it?

**Comment by harrislapiroff** [comment]
I _think_ I tried that and it didn't work. I could be wrong though. If that's the case, then I would call this a UI issue, since the dragging here is not clear.

**Comment by melinath** [comment]
I was always of the opinion that you should be able to drag in this view, but it was never implemented.

**Comment by harrislapiroff** [comment]
Oh, haha, gotcha. Well in that case, there was no way for me to assign the T shirt, I'm pretty sure.

**Comment by melinath** [comment]
Yeah, you have to go into the attendee and assign items there. It's pretty clunky / unintuitive.

**Comment by harrislapiroff** [comment]
No no, I did that. There was no option to add the t-shirt.

**Comment by harrislapiroff** [comment]
OH SHIT THERE IS.

**Comment by harrislapiroff** [comment]
Okay, I didn't see that.

**Comment by harrislapiroff** [comment]
Okay, yeah, let's call this a UX enhancement and not a bug.

**Comment by melinath** [comment]
I feel like the fact that even *you* (and @nmorduch?) couldn't figure that out does mean there's a serious issue :-p

**Comment by harrislapiroff** [comment]
Although whatever @nmorduch was running into was still a bug, but I can't reproduce it. Maybe she can.

**Comment by nmorduch** [comment]
The bug I had:

I had two passes and an item. The item was by default assigned to the first attendee, but I wanted it to go on the second attendee, so I removed it from the first attendee. When I got to the second attendee, there was no field for selecting the item.

**Comment by melinath** [comment]
Hmm. It looks like it's not possible to actually un-assign items from an attendee. And if all items are assigned, other attendees don't have a field displayed to them.

**Comment by melinath** [comment]
The UI/UX should be a separate ticket.
