### ISSUE TITLE
Additional notes about your order field

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#388]
We should offer a freehand way for an attendee to communicate information to an organizer. Adding a field somewhere in the checkout process for "Additional notes about your order" might be a good way to do it.

**Comment by melinath** [comment]
So in addition to #242, an arbitrary field for an organizer to store notes, we should also have an arbitrary field for attendees to store notes?

**Comment by nmorduch** [comment]
Yes :)

**Comment by harrislapiroff** [comment]
Yeah, that's what we were thinking. Stuff like, "we'll be arriving late on saturday" or whatever

**Comment by melinath** [comment]
Moving this waaaay back since it's covered by custom data.

**Comment by melinath** [comment]
Maybe we could even close this? @harrislapiroff

**Comment by harrislapiroff** [comment]
Yeah, I think custom forms obviates this. :+1:
