### ISSUE TITLE
Use parentheses for negative in order summary

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#393]
Fees of "-$5" is confusing. Especially when it's "$-5" :p
But it is good to note that in the sum it is counted as negative.

**Comment by melinath** [comment]
We currently handle this formatting with a template tag in zenaida. That could hypothetically move to brambling... it was in zenaida because of argus, IIRC

**Comment by melinath** [comment]
Resolved with merge of #504
