### ISSUE TITLE
Stepbar only shows two items in unexpected circumstance

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#395]
![screenshot 2015-03-06 07 47 11](https://cloud.githubusercontent.com/assets/296631/6525576/03240608-c3d5-11e4-89e6-13a9718ca435.png)

This might be related to the fact that I have some passes which are already purchased (I'd have to do more testing to confirm), but I am going through the purchasing process again to purchase new items. The attendee screen shows the full stepbar as expected.

![screenshot 2015-03-06 07 49 58](https://cloud.githubusercontent.com/assets/296631/6525602/665c2b9c-c3d5-11e4-91b9-1dc15522930e.png)

This may be resolved by #260, but that's potentially a few months off.

**Comment by melinath** [comment]
Pretty sure that this is resolved as a side effect of the changes in #478.

**Comment by melinath** [comment]
Yeah, this doesn't happen any more. All tabs are always displayed.
