### ISSUE TITLE
Item assignment UI unintuitive

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#396]
See the discussion in #387.

**Comment by nmorduch** [comment]
Updates to design should a distinction between already-bought things and new things. Consider the striped scrim. (take a look at #395 for this problem in action)

**Comment by harrislapiroff** [comment]
Probably there should still be the ability to reassign items that were already purchased and add items to passes that were already purchased, though, which might make the striped scrim impractical or misleading.

But, yes, that screen is extremely confusing if you've already purchased items. Which will hopefully be resolved with #260 although that's still a few months off.

**Comment by harrislapiroff** [comment]
Or maybe not. I was imagining scrimming out the entire attendee, but I guess you were probably just picturing doing it on an individual item basis.

**Comment by harrislapiroff** [comment]
This is going to be a thorny UI problem. Drag and drop is sort of attractive as an option, but I'm concerned that still won't be very intuitive and definitely won't work on mobile. I can't think of any examples of this sort of UI, but maybe someone else can? We may need to think/code up a unique interaction for this.

**Comment by harrislapiroff** [comment]
My inclination on this, after some thought, would be to be able to see items in a list and have a popover (like a dropdown, basically) when you click on one which would let you select an attendee or add a new one. On mobile this could just be a modal.

**Comment by harrislapiroff** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/296631/10264746/64d9dcec-69e3-11e5-830a-85d47078827b.jpg)
