### ISSUE TITLE
Better icon for refund, with help text

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#398]
http://fortawesome.github.io/Font-Awesome/icon/undo/ looks better than the refreshy option in the list 

![undo](https://cloud.githubusercontent.com/assets/1051450/6530630/7872c540-c400-11e4-8a32-19cc98cf94f4.png)

And there should be text next to it because no icon is going to be clear.

**Comment by melinath** [comment]
Resolved with merge of receipt redesign.
