### ISSUE TITLE
Display multiple transactions on shopping summary page

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#402]
The receipt-like list of things bought on the order should be split up so that there is one list for each transaction. There should, if possible, also be something saying whether payment for each transaction has been received.

**Comment by harrislapiroff** [comment]
It might even be nice to have receipt detail pages for each transaction or at least a tabbed interface. Maybe one of the tabs can be overall summary and display the sort of combined data we currently display.

**Comment by nmorduch** [comment]
I was thinking that would get rid of the nice overall summary but I think what you're suggesting, having a tab for the summary, is a good solution. I was thinking of having a nav on the left like in attendee assignment

**Comment by harrislapiroff** [comment]
:+1:

**Comment by harrislapiroff** [comment]
Another way of thinking about this ticket might be that there should be a distinction between your transaction summary (records of what you purchased, when, how the financial transaction was carried out, and whether it was refunded) and your inventory (what you currently own). We might even want a new (separate) inventory view if it isn't combined into this view.

**Comment by harrislapiroff** [comment]
Although that's actually a separate ticket, I suppose. Just spitballing.

**Comment by melinath** [comment]
The order summary view should absolutely have a list of transactions and a list of inventory (including attendee assignment) side-by-side. I think it would make sense to have a separate view for details on each transaction, plus linking to the item assignment / data editing views.

**Comment by melinath** [comment]
Resolved with merge of #504
