### ISSUE TITLE
Changing the value of "Collect survey data" can strand already checked out users.

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#405]
Steps to reproduce:

1. Create an event with a pass that does not collect survey data.

2. Complete checkout as a user.

3. Change the event to require survey data.

4. Return to checkout screen. There's no escape:

   ![screenshot 2015-03-12 12 20 47](https://cloud.githubusercontent.com/assets/296631/6622308/3c608568-c8b2-11e4-9d5f-9fad8b634c38.png)

**Comment by melinath** [comment]
this may have been resolved by #478, since that refactored the workflows to eliminate two-button bars like this.

**Comment by melinath** [comment]
@JCattera could you confirm that this is resolved?

**Comment by JCattera** [comment]
This seems to have been resolved for me, as I registered for an event without survey data, enabled the survey data, and then checked my registration without it getting stuck.
