### ISSUE TITLE
Chosen + Formset = D:

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#406]
When dynamically creating a new item in a formset, all the chosen's generated HTML seems to get duplicated, but the chosen behavior does not, basically rendering any dropdown selects on dynamically created items useless. :(

See this in action when creating new item options on the item editing view.

* [x] Item options
* [x] Form fields

**Comment by melinath** [comment]
User ran into this.

> When creating fields for a form, the "Field Type" drop down worked for the first two fields but not for subsequent ones. Nothing happens when I click on the arrow. ... but then after messing around with "Field Type" on several fields I tried to create a new field and this time the "Field Type" drop-down came up opened, and wouldn't close!

We should probably fix this at long last.

**Comment by harrislapiroff** [comment]
The correct solution _would_ be to reinstantiate chosen at the moment a new form is created on that new form specifically. This is complicated by the fact that chosen _does_ get instantiated on the empty form and therefore the HTML gets copied over with none of the appropriate behavior. The correct approach therefore must involve _not_ instantiating chosen on the empty form. The correct approach probably is:

* Make the empty form _not_ part of the DOM, maybe as templates included between `<script>` tags, such that chosen does not get called on it.
* Call chosen as a callback when the new form is created.
