### ISSUE TITLE
Event Frozen, unpublished

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#412]
When does an event get frozen? I managed to get an event frozen, unpublished.

![screenshot 2015-03-18 12 29 47](https://cloud.githubusercontent.com/assets/296631/6713712/8c06ba94-cd6a-11e4-8c41-e61527dc1b16.png)

**Comment by nmorduch** [comment]
Maybe you were bad and looked like spam
Maybe we don't like you very much

**Comment by melinath** [comment]
It gets frozen on first sale.

**Comment by nmorduch** [comment]
I think probably we should remove the button when it freezes? And also fix this bug.

**Comment by melinath** [comment]
I think it makes the UI clearer to keep the button in play with hover text. Also it makes it super obvious when errors like this happen.

See also #235.

**Comment by nmorduch** [comment]
We should at least change the message to something like "Event cannot be unpublished because sales have already been made."  Because "Event is frozen" is entirely opaque. Maybe in the long run what we should do is get rid of the unpublish button but have a button for halting registration on your event? Because that is really what you want to do there.

**Comment by harrislapiroff** [comment]
I like that message ^

@melinath Can it not get frozen if it's not published yet? Or can freezing only prevent unpublishing and not prevent publishing? I think this happened because I (as an organizer) did some test orders before publishing the event. I can try to reproduce it to double-check, though.

**Comment by melinath** [comment]
@harrislapiroff I think that is a reasonable analysis of what could have happened. It looks like (as we suspected) the event always gets frozen on sale, whether or not the event is published. I think limiting that to published events would be a reasonable solution.

**Comment by harrislapiroff** [comment]
Bumping this because I just ran into it again.

**Comment by melinath** [comment]
OH HEY I figured this out :-/ it gets frozen if an organizer tests the checkout process before publishing. Hahaha.

**Comment by harrislapiroff** [comment]
I said that seven months ago...

**Comment by melinath** [comment]
So you did. And I agreed with your assessment. And then I forgot completely apparently. Hah. Sorry.
