### ISSUE TITLE
Compressor + Libsass + Autoprefixer

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#430]
It might be time to see if we can get completely away from using Compass and then successfully use Compressor with Libsass and Autoprefixer to automatically compile CSS on the fly.

Some potential leads:

* [Torchbox's Compressor Libsass processor](https://github.com/torchbox/django-libsass) - This looks reliable.
* [Django Compressor Autoprefixer](https://pypi.python.org/pypi/django-compressor-autoprefixer/0.0.1) - This doesn't...

**Comment by harrislapiroff** [comment]
This functionality is currently active on #440.

**Comment by melinath** [comment]
Merged in with ece735235ed6e99e7f98cba346f3a67dbacb52df.
