### ISSUE TITLE
Social media integration with marketing pages

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#434]
We should have OpenGraph tags for our marketing pages. Currently when we share http://dancerfly.com/ on Facebook, it picks an image and description from our events. We can do better, especially once we've got some visual elements...

![screenshot 2015-03-27 11 10 27](https://cloud.githubusercontent.com/assets/296631/6870353/e2f0e420-d471-11e4-9695-0d60ad529f9d.png)

**Comment by melinath** [comment]
@nmorduch are you interested in learning [OpenGraph](http://ogp.me/)?

**Comment by nmorduch** [comment]
@melinath I mean, I've used OpenGraph tags before. We just haven't thought so much about marketing pages before.

**Comment by melinath** [comment]
Oh. Hah. Sorry for the incorrect assumption.
