### ISSUE TITLE
Event/Item Description Formatting

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#441]
It might be nice to give organizers some minimal formatting options for to avoid unformatted blocks like:

![screenshot 2015-04-01 13 39 54](https://cloud.githubusercontent.com/assets/296631/6947361/9e0c52b6-d874-11e4-93bb-d9f29874ba28.png)

Maybe via a WYSIWYG editor like CKEditor?

**Comment by harrislapiroff** [comment]
OTOH will users make things uglier with formatting?

**Comment by melinath** [comment]
I think we should definitely provide basic formatting, probably via ckeditor. We should also auto-shrink the text...

**Comment by harrislapiroff** [comment]
We do auto-shorten it, actually. I had it expanded. The shorten script will probably need some finessing either on the style end or the logic end to crop accurately if we support multiple text sizes.

**Comment by melinath** [comment]
Hmm, the shortening doesn't seem to be working for me.

**Comment by harrislapiroff** [comment]
Oh wait, you're right. :|

**Comment by melinath** [comment]
Actually, I don't think this is as high priority atm. It would be nice, but it's not super urgent. The description isn't really meant to be used in that way.

**Comment by melinath** [comment]
@harrislapiroff do we have a favorite text editor these days?
