### ISSUE TITLE
Address for check mailing in registration email doesn't include line breaks.

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#448]
Mine looks like this:

![screenshot 2015-04-03 13 27 03](https://cloud.githubusercontent.com/assets/296631/6985814/2ef2427c-da05-11e4-87d8-d9657f000c83.png)

**Comment by melinath** [comment]
That's odd... the `<br />` tags are definitely in the template, so they're probably being rendered... I guess something somewhere along the way is stripping them out?

**Comment by chigby** [comment]
@harrislapiroff Do you know if this is still happening? The email templates have undergone fairly significant changes since this issue was created.

**Comment by harrislapiroff** [comment]
I have no idea, honestly :\. Maybe we should have some views for sample renderings of emails?

**Comment by melinath** [comment]
We do have views for sample renderings of emails ;-)

**Comment by harrislapiroff** [comment]
jklol

**Comment by melinath** [comment]
It looks like this is resolved, looks like as part of #506.

![screen shot 2016-01-06 at 2 59 43 pm](https://cloud.githubusercontent.com/assets/299979/12157358/2fa45e24-b486-11e5-8b01-b4d7940fa4f7.png)

![screen shot 2016-01-06 at 3 00 31 pm](https://cloud.githubusercontent.com/assets/299979/12157374/49bbdd3c-b486-11e5-92d2-7f685f03bb85.png)
