### ISSUE TITLE
Can't inspect an accountless registration when logged in

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#449]
## Steps to reproduce:

1. register for an event without an account
2. log in as a user
3. click the URL from the email to view more details about your accountless registration

## Expected results:

See details about the registration

## Actual results:

404

(Note: you can still see the registration when you aren't logged in)

**Comment by melinath** [comment]
That was an intentional choice, but maybe one that doesn't make a lot of sense.

**Comment by melinath** [comment]
This was obviated a while back by the implementation of claiming orders.
