### ISSUE TITLE
Error during dwolla payment 

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#452]
There may be a bug in Dwolla payment which causes the error "No JSON object could be decoded". On its face, this *could* just indicate that the server isn't available. (The testing API was down around the same time.) It looks like our code works against the testing server, now that it's back up, so maybe it was a temporary glitch?

* [ ] Add logging of (non-confidential) data related to all failed payments
* [ ] Ask customer to re-purchase their pass.

**Comment by harrislapiroff** [comment]
http://en.wikipedia.org/wiki/Heisenbug

**Comment by melinath** [comment]
![bug3](https://cloud.githubusercontent.com/assets/299979/7129528/7579a410-e216-11e4-801a-698f0965664c.png)

**Comment by melinath** [comment]
This was resolved by 45df49d66aa6e7085d2a051c84a2fd80fcde4aff. (Yeah, it just needed a version increase.) Also I apologize for that terrible art.
