### ISSUE TITLE
Event panel lists should limit number they display

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#458]
As organizers manage more events and attendees attend more events, these panels are going to become unwieldy.

We should limit the events displaying in these panels to future/current events and limit the number. We can provide a "See all events" link at the bottom which would take you to a separate view with a complete (paginated?) listing.

![screenshot 2015-04-21 22 48 36](https://cloud.githubusercontent.com/assets/296631/7266508/911bf89a-e878-11e4-84f2-45af91eb4ed9.png)

**Comment by melinath** [comment]
I'm thinking more and more that these just shouldn't be visible from the homepage. I think "Your Events" should be "Browse Events", and that your orgs, events, and orders should be viewable on other pages.

For this ticket, I'd suggest just adding org / event pages (from the username dropdown menu). Order history would be a separate ticket. Side note: The org list should maybe list what payment methods are enabled and that should link to the org's payment settings.

**Comment by harrislapiroff** [comment]
I'm -1 on removing from the homepage unless there's a good reason to. I think that if I'm an organizer, accessing my own event is the #1 task I'm going to be trying to do every time I visit Dancerfly and it should be immediately accessible.

The case for keeping events you're registered for on the homepage is a little less clear, but I also don't see a good case for making them harder to find.

Past events should definitely be removed. But ideally accessible _somewhere_.

**Comment by melinath** [comment]
Part of my thought is also that it would free up space for a more advanced filter/search interface...

**Comment by harrislapiroff** [comment]
I actually think accessing one's own events is more common than filtering and maybe filtering should be relegated to an interior page when logged in, but I actually think they can coexist. I'd prefer to see a thin horiz filtering interface like Eventbrite

![screenshot 2015-12-18 09 44 31](https://cloud.githubusercontent.com/assets/296631/11903137/fc866128-a56b-11e5-9a4d-43584e2e669e.png)

or OKC

![screenshot 2015-12-18 09 45 35](https://cloud.githubusercontent.com/assets/296631/11903158/1de122cc-a56c-11e5-9323-cb6a83af0213.png)

(also, kinda weird that the token shows up as "Monogamy" even if the actual search criteria is "Monogamous: No")

**Comment by melinath** [comment]
Yeah, fair 'nuff.
