### ISSUE TITLE
Organization and Event editing views need cleanup

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#459]
(Once #447 organization branch is merged.) They're functional now, but not super fun to use. They should be cleaned up. Taking inspiration from GitHub's repo and organization settings might be a good place to start.

**Comment by melinath** [comment]
Ugh, yeah, it's really annoying that you can't go from event creation to organization updates to org detail.

**Comment by melinath** [comment]
Potentially related: #462

**Comment by melinath** [comment]
Closing for now due to merge of #463. More specific tickets may be opened in the future.
