### ISSUE TITLE
Stop breaking up event list.

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#460]
Breaking up the event list on the dashboard and org pages (especially on org pages) looks weird and seems unnecessary. I'd prefer to have a combined list that makes certain to include all upcoming events that a user is registered for as well as a few that the user is not registered for and indicates visibly (I'm picturing a green button that says "Registered!" and replaces the current "Edit registration" button) which events you are registered for.

**Comment by melinath** [comment]
Wouldn't that make it harder to find just events you registered for? I guess it doesn't matter *so* much since they'll hit the top of that list once they're most relevant...

**Comment by harrislapiroff** [comment]
At least on org pages this is a necessity because the current layout looks silly and is confusing with so few events. (Also I'm not sure if this is confusing or broken, but under "Events You Registered For" _all_ events I'm registered for show up, not just the ones for that organization.)

I think I also prefer a combined feed for the homepage, though I'm open to persuasion. I do want to spend a little time thinking about how to call out an access the events you are registered for. Maybe they can also be listed in a separate location.

**Comment by melinath** [comment]
+1 on changing it on the org pages, for sure. (That's broken.)

I like the idea of just having a separate page for events that you're registered for (or maybe only your events on the dashboard, and a separate page for browsing events).

Alternate options: we could look into implementing a full search page, and one of the options could be "events I'm registered for". But if we go in that direction, we'd need to somehow annotate the fact that someone is registered for an event, which could end up being a pain...

**Comment by harrislapiroff** [comment]
I might also be into a combined list that had events you were registered for on top—basically what we have now but without headings or repetitions.

**Comment by melinath** [comment]
This was resolved with the merge of #485.
