### ISSUE TITLE
Improve attendee / order table cell widths

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#473]
Right now, the table cells use the default behavior of shrinking as much as possible, which leads to really weird text flow. It would be great if we could make this behave better... not sure whether that's possible.

**Comment by harrislapiroff** [comment]
In my ideal world these tables will be more sophisticated, like a spreadsheet. In the meantime, we could use CSS to prevent text wrapping and even provide a button to toggle that on and off.

**Comment by melinath** [comment]
I don't think we want to *prevent* text wrapping, more like have a minimum width on all the fields. Or different minimums on different fields. Or something.

**Comment by melinath** [comment]
Preventing wrapping altogether could lead to the opposite problem where fields with a lot of text end up being SUUUUUPER long

**Comment by harrislapiroff** [comment]
Yeah, I mean, ideally they'd do the spreadsheet thing where they didn't wrap _and_ were cropped and you could click to view the whole value. (and maybe edit! grid editing!)

**Comment by melinath** [comment]
Okay... I think that's getting waaay ahead of what we need right now.

Here's what I propose: we add a way for ModelTables to specify cell widths, either as keywords (auto / small / medium / large) or as widths (auto / 100 px / etc), based on the column's field name. Does that sound like a reasonable implementation?

**Comment by melinath** [comment]
Would love to see this fixed. :-p

![screen shot 2015-09-15 at 6 03 58 pm](https://cloud.githubusercontent.com/assets/299979/9894067/5784a832-5bd4-11e5-8f09-7658331de4a9.png)

**Comment by melinath** [comment]
I'm marking this as closed for now. I know we want a more thorough solution long-term, but we can make a new ticket if/when it comes to that point.
