### ISSUE TITLE
Double org in list?

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#483]
On my dashboard:

![screenshot 2015-04-29 10 30 13](https://cloud.githubusercontent.com/assets/296631/7393278/d55cb89a-ee5a-11e4-8f64-2833888f146a.png)

Not 100% sure what's going on here. Both romp orgs appear to go to the same place. Maybe we need a call to `.distinct()` somewhere?

**Comment by melinath** [comment]
Offhand, I would say that a distinct() in `Person.get_organizations()` should solve it, but I can't seem to reproduce the behavior so I can't confirm 100%. (It looks like it could come up if someone were both an editor and an owner, but that doesn't result in a double entry for me.)

**Comment by melinath** [comment]
Oh, weird, adding *other* editors fucks it up.

**Comment by harrislapiroff** [comment]
On my dev machine it's even more severe.

![screenshot 2015-04-29 13 06 52](https://cloud.githubusercontent.com/assets/296631/7396625/9f598384-ee70-11e4-9380-066ae180a4d5.png)

I could give it a poke, unless you're already on it.

**Comment by harrislapiroff** [comment]
haha, ok

**Comment by melinath** [comment]
It looks like each additional editor added another version of the event - I'm guessing because one of the OR conditions (being the owner) was always True.
