### ISSUE TITLE
Thunderbird marking emails as spam

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#484]
Thunderbird apparently distrusts emails that contain URL links that go to a different location than the listed URL. It looks like this bug [dating back to 2006](https://blog.mailchimp.com/new-security-feature-in-thunderbird-triggered-by-click-tracking/) might be the culprit.

A few possible courses of action:

* Don't use Mandrill. (Not preferable. Mandrill is way easier to debug than our own SMTP server! Also we can do stuff like pause emailing and track click throughs!)
* Don't include an explicit URL at all in the HTML version of the email. (This may entail custom writing a non-HTML version of the email?)
* Include the explicit URL, but don't link it. (Is this possible or does it have to get autolinked somewhere along the way?)

**Comment by melinath** [comment]
We have to link the URL. Some clients autolink, but others don't – that's the issue we were running into with Manchester Lindy.

I think it could fix it if we just had the link be text – "Click here to verify your account" – but that's assuming the mismatch was the issue.

**Comment by melinath** [comment]
Hmm, that bug report seems to indicate that wouldn't be a fix, and that there is no fix, and that we should just make our emails prettier.

**Comment by harrislapiroff** [comment]
I've found a few references to the URL mismatch feature of Thunderbird when searching for "Mandrill spam thunderbird" so I think there's a strong possibility that that's the issue.

I was thinking we link the email in text _and_ provide a "If the link above doesn't work, copy and paste this into your URL bar," sort of thing that emails often do.

But also, it's 2015. Do we still need to do that? Can we just link some text? The only issue I see with that would be that we should provide a plain-text alternative.

**Comment by harrislapiroff** [comment]
Why wouldn't that be a fix? If the issue is a mismatch between the text of a link and the actual link, we could fix it by not having an actual link, no?

**Comment by harrislapiroff** [comment]
> That means if you send an innocent email newsletter to your subscribers with a complete URL spelled out in the email (for example, "Please visit us at http://www.mysite.com" ) and then you enable click tracking for the email, that link would set off the scam alert in Thunderbird. 

So we could avoid that by either not spelling out the URL or not having an HTML link on the spelled out URL. Right?

**Comment by melinath** [comment]
The bug report you linked indicates that it's an issue for text links as well.

>Scammers do this all the time. They’ll place a link in an email, such as "Verify Your eBay Password" but if you click it, you get taken to some evil website, where they steal your password, or download spyware onto your computer.

**Comment by melinath** [comment]
Or at least, that's how I read it. But it's not explicit, so.

**Comment by harrislapiroff** [comment]
I think that's just a poorly written paragraph. I don't see anything in the blog post that substantiates that.

**Comment by melinath** [comment]
Marking this as closed as part of #506.
