### ISSUE TITLE
Events showing up multiple times in panels

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#488]
I'm on branch `date-dates` and I can't migrate backward to check if this is a bug on master or a bug on this branch:

![screenshot 2015-05-03 13 47 03](https://cloud.githubusercontent.com/assets/296631/7446158/8bb72b12-f19d-11e4-9021-056766868527.png)

**Comment by melinath** [comment]
We already fixed that once on master, I thought. Was there a merge conflict and it got lost?

**Comment by harrislapiroff** [comment]
No, we fixed it with orgs on master. It might be a related issue though?

**Comment by harrislapiroff** [comment]
#483

**Comment by melinath** [comment]
Yeah, it's almost certainly the same issue.
