### ISSUE TITLE
Check payment deadline nonsensical on organization

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#490]
Currently, enabling payments by check requires inputting a "postmark by date" which made sense when payments were stored on the event, but is nonsensical now that payments are stored on the org and may have multiple events with different dates.

Not sure what the solution is.

**Comment by melinath** [comment]
I think the easiest would be to move that field back to Event and display it in the payment section if check payments are enabled (defaulting to a week before the event starts.)
