### ISSUE TITLE
Link to remote payment detail pages from transaction list

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#508]
From FDW:

> As icing, if the Stripe API gives you easy access to the Stripe payment ID, it might be pleasant to include a link to the Stripe dashboard page for that payment in your Finances view: https://dashboard.stripe.com/payments/{{ STRIPE_ID }}

I think this would be pretty easy to do, though not necessarily 100% future-proof... For Dwolla, the URL (seems to be) https://dwolla.com/activity#/detail/{{ REMOTE_ID }}.

**Comment by harrislapiroff** [comment]
We're currently storing transaction IDs that the service provides to us in the database, right? It's just a question of adding a column to the table for that link?

**Comment by melinath** [comment]
Yep.

**Comment by harrislapiroff** [comment]
:tada:
