### ISSUE TITLE
Set up Dancerfly support email

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#513]
This is something we've talked about doing... right now, folks get an email from hello@littleweaverweb.com when they sign up. Maybe it should be a dancerfly address? support@dancerfly.com?

**Comment by nmorduch** [comment]
I set up support@dancerfly.com a little while ago, as well as hello and info. All are equivalent right low to hello@lww. I'm going to start putting support@ into use in emailing.

**Comment by melinath** [comment]
Oh hey! This is totally done!
