### ISSUE TITLE
Item Deletion

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#533]
There's currently no way to delete an item, but there should be.

**Comment by melinath** [comment]
#337 (Caching values on BoughtItems) needs to be finished before we give people this power. :-p

**Comment by harrislapiroff** [comment]
Ah ha, that's why this doesn't exist!

**Comment by melinath** [comment]
I mean... you can delete ItemOptions, which has essentially the same problem. :-p So maybe this doesn't have to wait? I've just been getting increasingly nervous about that other ticket recently.
