### ISSUE TITLE
Issue with "Field Type" Dropdown

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#539]
From user:

>When creating fields for a form, the "Field Type" drop down worked for the first two fields but not for subsequent ones.  Nothing happens when I click on the arrow.  ... but then after messing around with "Field Type" on several fields I tried to create a new field and this time the "Field Type" drop-down came up opened, and wouldn't close!

**Comment by harrislapiroff** [comment]
This bug also applies to item editing, unfortunately.

**Comment by melinath** [comment]
Can you shed some more light on what the actual bug is?

**Comment by melinath** [comment]
... on second thought, you're probably still working on that part.

**Comment by melinath** [comment]
I guess I mostly mean, is the description of how to reproduce actually accurate?

**Comment by harrislapiroff** [comment]
No, the problem is easy. Chosen has to be instantiated with javascript. Our current scripts instantiate it on all appropriate selects on domready, but selects that get created _after_ domready (i.e., when you dynamically create a new form on a formset) don't have it instantiated.

**Comment by melinath** [comment]
Oh, so it's a duplicate of #406

**Comment by harrislapiroff** [comment]
Oh. Yes.

**Comment by melinath** [comment]
Closing as a duplicate.
