### ISSUE TITLE
Hidden errors?

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#540]
From a user:
>Shopping cart review - If you don't check the consent box, and then click save, it scrolls to the top.  The indications of an error are off screen.  THIS IS A MAJOR BUG, since it might lead some users to conclude that they were completely registered.

I think maybe this means the attendee basic info page?

**Comment by harrislapiroff** [comment]
I'm pretty sure he does. This should be roughly the same solution as #253.

**Comment by harrislapiroff** [comment]
In fact, `{% include "brambling/forms/_top_error_list.html" %}` is probably exactly the line needed.
