### ISSUE TITLE
Under some circumstances, attendee housing "next step" button displays twice

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#546]
I'm not 100% sure what the circumstances are that cause this, but I suspect it has to do with going through the checkout process more than once.

As seen in this screenshot:

![screenshot 2015-06-15 17 28 13](https://cloud.githubusercontent.com/assets/296631/8171180/0c3c6060-1384-11e5-89b1-ba684397130a.png)

This seems like a pretty severe UI bug as well, because one of the buttons is a submit for the form and the other is a link to the next step that does not submit the form.

**Comment by harrislapiroff** [comment]
Did we fix this?

**Comment by melinath** [comment]
I feel like we may have?
