### ISSUE TITLE
Delete test/duplicate/mistake orders

### ISSUE THREAD

**Issue by spilzer** [littleweaver/django-brambling#552]
There should be a way to delete orders that were placed during testing or by mistake. Otherwise the CSV file will need to be manually changed every time it is downloaded, which is a pain for organizers, especially those not particularly well versed in spreadsheet management.

**Comment by melinath** [comment]
I think this problem may be covered by #512 already.

**Comment by melinath** [comment]
Feel free to reopen if not.
