### ISSUE TITLE
Sales summary should be useful

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#556]
0. Order item options by item
0. Give total sales per item

Bonus points for collapsing item options under items 

Should help with #555

**Comment by melinath** [comment]
Extra bonus points if it's more obvious that the options are links :-p

**Comment by nmorduch** [comment]
Wow I did not even do number 2 on my list oops

Well because I couldn't.
But I should have said the commit closed this.

**Comment by nmorduch** [comment]
@spilzer this should be more useful for you soon!
