### ISSUE TITLE
CSV Issues

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#558]
@spilzer mentioned to me the other day that there might be some issues with Excel reading Dancerfly-produced CSVs? Or maybe it was with Google Sheets reading Dancerfly-produced CSVs? I can't remember. Either way, this should be investigated.

**Comment by melinath** [comment]
Just got this from a user:

>When attempting to download csv I get this message "file format & export csv don't match. The file could be corrupted or unsafe...."
>And when I click on it anyway
>"It is a SYLK file but cannot load it"

**Comment by harrislapiroff** [comment]
That tracks with what @spilzer told me. Sounds urgentish. Will look into soon.

**Comment by melinath** [comment]
The user looked into it some more and found the following: https://support.microsoft.com/en-us/kb/323626

And was able to open the file following those instructions... which were for Office 2003. Do we want to support versions that old? Maybe we should just instruct people having issues to use libreoffice or google drive?

**Comment by melinath** [comment]
Or we can just be fine with the xlsx alternative being available.

**Comment by harrislapiroff** [comment]
I want to look into if we can either write XLS files or if the excel dialect of the python CSV writer fixes this.

**Comment by harrislapiroff** [comment]
We don't currently provide xls do we?

**Comment by melinath** [comment]
No; ticket #572 is currently tracking that issue.

**Comment by harrislapiroff** [comment]
Ah ha

**Comment by melinath** [comment]
Resolved with merge of #628
