### ISSUE TITLE
Publish/Unpublish buttons wonky

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#563]
From feedback:

> Publish/unpublish buttons appear to do what they promise to, but land the user on a n HTTP 500 page.

**Comment by harrislapiroff** [comment]
Is this still true? Looks like this feedback came in a while ago.

**Comment by melinath** [comment]
@JCattera could you look into this one? It might already be fixed, but if not it should be relatively easy to fix.

**Comment by JCattera** [comment]
The Publish/Unpublish works perfectly for me on all pages of the organizer, so I assume it's already been fixed.
