### ISSUE TITLE
Send receipts per-transaction rather than per-order

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#607]
In other words, when you make a transaction, you should get an email for *just* that transaction – how much you paid and what you bought – not for every transaction / item associated with that order.

**Comment by harrislapiroff** [comment]
:+1:

**Comment by chigby** [comment]
The receipt emails make a few references to the order code. Should we just use the code from the order that the transaction belongs to, add a per-transaction code, or something else?  I lean towards the first option but I don't know if people have strong feelings about this.
@harrislapiroff @melinath

**Comment by melinath** [comment]
@chigby use the code from the order the transaction belongs to.

**Comment by harrislapiroff** [comment]
👍

**Comment by chigby** [comment]
Should this also apply to the Order Alert emails? Are the expectations of event organizers different from the person actually spending the money?
@melinath

**Comment by melinath** [comment]
@chigby hmm, good question. I think that probably the order alerts to organizers should also be per-transaction, yes.
