### ISSUE TITLE
remove interests field in profile

### ISSUE THREAD

**Issue by feonixf** [littleweaver/django-brambling#612]
https://dancerfly.com/profile/

- Add search by dance type / location / date range / etc field on main events listing page

maybe it could look similar to this! 

http://8tracks.com/explore/Beyonc%C3%A9
![screen shot 2015-09-12 at 5 11 47 pm](https://cloud.githubusercontent.com/assets/14251671/9833763/2960e4b6-5972-11e5-8c60-2f93e2f93d5d.png)

**Comment by melinath** [comment]
Searching for events is a separate feature covered (roughly) by #145
