### ISSUE TITLE
Send more verbose data to payment processors

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#627]
I thought we already had a ticket for this, but I can't find it now, so I'm making a new one.

**User Story**

I'm a dance organizer and I want to give an attendee a partial refund. Because Dancerfly doesn't yet support partial refunds, I need to do this through Stripe. I have to look up the order number on Dancerfly and then find that order number on Stripe. It'd be better if I could just search stripe for an attendee's name.

**Implementation**

We should pass more data to payment processors. Minimally, a comma separated list of attendees for search purposes would be useful. If the payment processor can accept more complex data, that would be awesome too.

**Comment by melinath** [comment]
The previous ticket is #565. I'll leave it to you to resolve.

**Comment by harrislapiroff** [comment]
Ah ha, thanks. I'll close this as dupe then.
