### ISSUE TITLE
Supply OG info for event on event pages

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#648]
When a person shares a dancerfly event on Facebook, the event's information isn't what shows up on FB. Instead, it's just "Dancerfly." This is silly and also not good. It should be the event's info. See screenshot. (Also, side note, the default image is not great...)

![screen shot 2015-10-01 at 5 58 52 pm](https://cloud.githubusercontent.com/assets/299979/10237438/44bfb9f0-6866-11e5-992c-99ff67d23a72.png)

**Comment by chigby** [comment]
I tested this out in the [Facebook crawler debugger](https://developers.facebook.com/tools/debug/og/object/) and for a variety of events everything seemed fine. 

The documentation implies that if the crawler can't load the image it will fall back to a default one or infer one from tags on the page -- which maybe happened in this case? I think it might be worthwhile to supply a nicer default image, one that at least fits the dimensions for a facebook post.

**Comment by melinath** [comment]
Checked in with the folks who were having the issue and it seems to be resolved for them? I feel like we ran into something like this with our blog maybe? Or maybe it was just super-old caching and checking on the debugger cleared it up.
