### ISSUE TITLE
Strange Open Graph image URLs

### ISSUE THREAD

**Issue by chigby** [littleweaver/django-brambling#652]
Events with banner images enabled (and who doesn't want banner images?) acquire meta tags that look something like this:

`<meta property="og:image" content="https://dancerfly.com/media/./Clouds.jpg" />`
[Source](https://dancerfly.com/rain/rain2016/order/shop/)

Which, to my eye, looks like it has an extraneous dot. 

I can't say that this would ever cause problems, but I also don't like it.

**Comment by melinath** [comment]
`.` means 'stay in the current directory'. Essentially the issue here is that banner images are just stored in the root media directory, and this is how django handles that. It's messy and looks weird and we shouldn't do it, but it also shouldn't break anything.
