### ISSUE TITLE
Double clicking add-to-cart will add items twice

### ISSUE THREAD

**Issue by chigby** [littleweaver/django-brambling#665]
If you double click on an item in the shop, it will add two of them to your cart. I think this is generally not expected and, if not noticed before checkout, could lead to incorrect purchases.

Also, does not interact well with items of limited quantity:

![screen shot 2015-10-12 at 14 28 39](https://cloud.githubusercontent.com/assets/561931/10435457/1afe5ece-70ee-11e5-9b22-c8748ab6dea4.png)

**Comment by melinath** [comment]
Oh hey this was resolved  by the merge of #666.
