### ISSUE TITLE
Custom forms overview UI

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#695]
The forms list page is uneven if there are different numbers of forms in each type. They should either be in two separate rows or in four columns.

![screenshot 2015-11-03 17 03 02](https://cloud.githubusercontent.com/assets/296631/10923075/e0bd6492-824c-11e5-9b1d-4cbc01c16146.png)

**Comment by melinath** [comment]
Should we maybe only allow a single form in each category? That would drastically simplify the interface... in fact at that point we could probably just list fields *on* the form rather than listing forms. We don't currently do anything special with multiple custom forms and maybe we shouldn't?

**Comment by harrislapiroff** [comment]
:+1: That would be fine with me. Esp if we ultimately integrate pages and headings into forms. (Though I think maybe initially the reason we allowed multiple forms was for form logic? But I'm meh on form logic anyway.)

**Comment by harrislapiroff** [comment]
In light of the above comment thread, I am closing this ticket as wontfix, since we're gonna redo this UI anyway.
