### ISSUE TITLE
Split event settings into multiple pages

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#726]
Even on desktop (but especially on mobile) the event settings page is long and hard to deal with. It's not really clear what you're gettting when you go there or where on the page you'll be able to find it. I think a good solution could be to split it into several sections:

1. Basic information - name, urls, description, dates, location, currency?, timezone
2. Design - banner image(s) (see #700) and any other design options we add in the future
3. Registration - cart expiration, event privacy, etc.
4. Permissions - editors; this could maybe stay in basic info?
5. Payment - currency?, check postmark date, list of payment options (maybe even the actual form from org for people with the right permissions?)

Side note: 1, 2, and 3 could be part of an initial setup process (see #462).

But the big questions for me are:

1. Is this really a thing we should do? I think it is, especially as we add even more configuration options to events, but I'd love a second.
2. Where the fuck should we put the navigation? We already have 8 items in the admin nav; this would take that up to 12. We could maybe save some space by putting 'copy event' somewhere else - maybe on the basic information page? (It should probably go wherever we end up wanting to put the 'delete' button - see #254.) We could do some kind of nested navigation, maybe tabs for the various new pages, but that feels like it could just make things even more complicated.

Though along those lines, we could make the *entire* nav for events more hierarchical - for example, splitting it up into Summary, Settings, "Related Objects", and Reports. But again, that seems like it makes things just harder to find. :-/

**Comment by melinath** [comment]
@harrislapiroff, @feonixf, @nmorduch I would love to hear your design thoughts on this one...

**Comment by melinath** [comment]
FWIW Eventbrite (for example) has a huge sidebar menu that has collapsible sections, as well as a horizontal menu at the top and various buttons in the main content area.

![eventbrite testing](https://cloud.githubusercontent.com/assets/299979/11997965/c7262dae-aa40-11e5-9a6f-087ca0e6a8d6.png)

**Comment by harrislapiroff** [comment]
I love the idea of a large sidebar with collapsible sections. That's also the Wordpress approach and I think people are familiar with it and find it fairly usable.

**Comment by harrislapiroff** [comment]
I am also in super favor of breaking the settings into multiple pages.

**Comment by nmorduch** [comment]
Right so collapsible sidebar where each section is a page and each link under it brings you to that part of the page??? That sounds good to me. As does the general reorganization.

It would also be cool to show a preview of the design stuff?? But that is a different issue.

**Comment by feonixf** [comment]
Yup, collapsible all the way.
