### ISSUE TITLE
Support for merging conflicting orders

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#751]
Right now, conflicting orders prevent users from seeing all of their purchases, which is *basically* a data loss bug. We need to fix this ASAP.

I'd suggest that we provide a merging interface that basically assigns all the transactions & items on the old order to the new order and strips their attendees, then directs the user to the assignment page. Maybe we should also transfer attendees? But I wouldn't want to end up in a situation where the event has duplicate attendees mucking up the works.

We should also transfer hosting data that is on the old one but not the new one. And we should provide a message saying what was transferred. And we should delete the old order.

**Comment by melinath** [comment]
Report here: https://www.facebook.com/events/1558873821063246/permalink/1691611431122817/

**Comment by harrislapiroff** [comment]
Ultimately we should probably support associating multiple email addresses with an account. Maybe doesn't need to be immediately though.

**Comment by melinath** [comment]
That also wouldn't solve this issue... ;-)

**Comment by harrislapiroff** [comment]
Oh. Maybe I misunderstood!

**Comment by melinath** [comment]
Resolved with merge of #753.
