### ISSUE TITLE
Add a warning if payment by check date is passed or blank

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#766]
On the event Settings & Payment view:

![screenshot 2016-02-23 17 04 06](https://cloud.githubusercontent.com/assets/296631/13268256/7d4f4ec4-da4f-11e5-8da7-29dc1cece53c.png)

If the date is blank or set to something in the past, then payment by check will not show up as an option to registrants. This makes sense, but it may not be immediately obvious to an organizer.

**Comment by harrislapiroff** [comment]
This just confused at least one organizer. Bumping its priority. :)

**Comment by raq929** [comment]
How would you feel about making the check box into the no entry look instead?
If you want to go with a warning box, what do you want it to look like? @harrislapiroff

**Comment by harrislapiroff** [comment]
I think a warning box might be preferable, because I imagine just having the check box in red would cause someone to try to fix it in org settings as instructed (which would not work). I think maybe a yellow alert under or next to check "Checks must be postmarked by" field that says "Postmarked date has passed. Payment by check will not be shown as a payment option."

**Comment by raq929** [comment]
Yeah, that makes sense. Thanks!

**Comment by harrislapiroff** [comment]
UGH CHECK BOX WHAT THE HECK, WE'RE GONNA NEED A DIFFERENT WORD FOR THAT
