### ISSUE TITLE
Set up tasks to be per-server rather than using -H on the command line

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#790]
Right now, we deploy like so:

```
fab -H <server_name> deploy # Deploys a clone of production to the given server
```

Which is fine, except that it doesn't let us do things like run a task as if the current server is a staging vs production server. How this _should_ work:

```
fab production deploy # Deploys a clone of production to the production server (which fab knows something about)
fab staging deploy # Deploys a staging version to the staging server (which fab knows something about0
```

See the following for information / inspiration:

* http://docs.fabfile.org/en/latest/usage/execution.html
* http://djangotricks.blogspot.com/2010/05/deployment-using-fabric.html

**Comment by melinath** [comment]
If we can get this nailed down, it'll help us do things like have a command to overwrite the database that can't be run on production. (See #776) It'll also let us have separate reporting in newrelic for staging and production.

**Comment by harrislapiroff** [comment]
:+1: to this. I live in constant fear of accidentally deploying to the wrong server.

**Comment by melinath** [comment]
Ideally this would work with private keys, but without assuming that a particular ssh config exists and without assuming that a particular ssh config points to the correct server. I.e. if the staging server became the production server and someone didn't update their config and tried to push to staging, that should error out fast.

Possible implementations that come to mind:

* Keep track in fabric of what the server ip SHOULD be for each env and check. (i.e. production should be ip <whatever>. Current ip is <something>. Do those match?) Advantage: less work. Disadvantage: people with old code could accidentally deploy staging to master (hypothetically).
* Keep track on the server (maybe in some kind of conf file?) whether the server is production or staging. This conf can be updated with a special command. In other commands, verify conf existence & contents match expected before proceeding. Advantage: server 'knows' what it is. Disadvantage: Random-ass file nobody would expect to exist does weird shit.
