### ISSUE TITLE
Organizer notes broken

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#831]
From an organizer:

> Got a 500 error when I clicked button &quot;save notes&quot; trying to add &quot;Notes&quot; in the notes box with the order items in it. (Adding the note in the &quot;notes&quot; box without the items in the order listed in it worked – though no confirmation was displayed and it sort of looks like nothing has happened. I can confirm it worked by viewing the order in the &quot;orders&#39; link on the left navigation bar)

> To follow up on previous submission – the problem is when I try to add notes to the &quot;Attendee&quot; notes box, it gives a 500 error. But when I add notes to the order it allows it. Please fix as this is really obnoxious if I need to add notes to an attendee in a multiple-attendee order and also means I have to track special orders in lots of different places. Thanks!

**Comment by emilyhorsman** [comment]
Reproduction instructions:

1. Create an event with an item
2. Have a user order that item
3. As an organizer, navigate to the event management, select `Orders` under `Data` and attempt to save item-related notes (the bottom one in the following screenshot, not the top one).
<img width="320" alt="screen shot 2017-05-15 at 4 30 24 pm" src="https://cloud.githubusercontent.com/assets/3536823/26083634/d7b6ce90-398b-11e7-95c2-246b3674c533.png">
