### ISSUE TITLE
Negative item availability counts

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#871]
This probably shouldn't be possible:

![screen shot 2017-06-07 at 2 47 18 pm](https://user-images.githubusercontent.com/296631/26895676-53636fe2-4b90-11e7-83b0-a5f158da168e.png)

**Comment by melinath** [comment]
Closing as duplicate of #843

**Comment by harrislapiroff** [comment]
JK #843 covers this--- dammit @melinath is too fast for me.
